pr: none

trigger:
  branches:
    include:
      - '*'

variables:
  tag: '$(Build.SourceBranchName)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Login to docker registry
      inputs:
        containerRegistry: 'dobe.cc Docker registry'
        command: 'login'
    - task: Docker@2
      inputs:
        containerRegistry: 'dobe.cc Docker registry'
        repository: 'cj'
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourcesDirectory)/cj/Dockerfile'
        tags: |
          $(tag)
          latest
