version: '3'
services:
  strapi:
    image: strapi/strapi:3.5.4
    volumes:
      - ./app:/srv/app
    ports:
      - '1337:1337'
    environment:
      - ADMIN_JWT_SECRET=some_secret_value
      - JWT_SECRET=some_secret_value
